# Generated by Django 2.0.6 on 2018-06-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_pubs', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='Удалённый Пользователь', on_delete=django.db.models.deletion.SET_DEFAULT, to='webchat.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('admin', models.ForeignKey(default='Удалённый Пользователь', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='admin', to='webchat.Profile')),
                ('users', models.ManyToManyField(to='webchat.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webchat.Rooms'),
        ),
    ]
